
using device cuda
label: klement blev underligt ängslig, när fiskaren berättade detta.
  0%|                                                                                                                                                                                                                                           | 0/1080 [00:00<?, ?it/s]Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_run.py", line 170, in check_status
    status_response = self._interface.communicate_stop_status()
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\interface\interface.py", line 127, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 395, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_run.py", line 152, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\interface\interface.py", line 138, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 405, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\cerik\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
